### ISSUE TITLE
nvme/opal: intermittent AUTHORITY LOCKED OUT error

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1002]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_47783.html

Relevant section of log:

************************************
START TEST SUITE ./test/nvme/nvme_opal.sh
************************************
 01:10:20	# xtrace_enable
 01:10:20	# ./test/nvme/nvme_opal.sh
  01:10:20	# xtrace_enable
 01:10:20	# spdk_tgt_pid=3294208
 01:10:20	# trap 'revert; killprocess $spdk_tgt_pid; exit 1' SIGINT SIGTERM EXIT
 01:10:20	# /var/jenkins/workspace/NVMe_tests/opal_autotest/spdk/app/spdk_tgt/spdk_tgt
 01:10:20	# waitforlisten 3294208
 01:10:20	# '[' -z 3294208 ']'
 01:10:20	# local rpc_addr=/var/tmp/spdk.sock
 01:10:20	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
 01:10:20	# xtrace_disable
 01:10:20	# PREV_BASH_OPTS=ehxBE
 01:10:20	# set +x
Starting SPDK v19.10-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid3294208 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 639:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
 01:10:21	# xtrace_enable
 01:10:21	# ((  i == 0  ))
 01:10:21	# return 0
 01:10:21	# opal_init
  01:10:21	# /var/jenkins/workspace/NVMe_tests/opal_autotest/spdk/scripts/gen_nvme.sh --json
  01:10:21	# jq -r '.config[].params | select(.name=="Nvme0").traddr'
 01:10:21	# bdf1=0000:84:00.0
 01:10:21	# /var/jenkins/workspace/NVMe_tests/opal_autotest/spdk/scripts/rpc.py bdev_nvme_attach_controller -b nvme0 -t pcie -a 0000:84:00.0
EAL:   using IOMMU type 1 (Type 1)
nvme0n1
 01:10:21	# set +e
 01:10:21	# /var/jenkins/workspace/NVMe_tests/opal_autotest/spdk/scripts/rpc.py bdev_nvme_opal_init -b nvme0 -p test
nvme_opal.c:1845:spdk_opal_cmd_take_ownership: *ERROR*: start admin SP session error 18: AUTHORITY LOCKED OUT
nvme_opal.c: 429:opal_response_parse: *ERROR*: Bad header length. cp: 0, pkt: 0, subpkt: 0
nvme_opal.c: 638:opal_parse_and_check_status: *ERROR*: Couldn't parse response.
vbdev_opal_rpc.c:  87:spdk_rpc_bdev_nvme_opal_init: *ERROR*: Take ownership failure: 18
request:
{
  "method": "bdev_nvme_opal_init",
  "req_id": 1,
  "nvme_ctrlr_name": "nvme0",
  "password": "test"
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "Internal error"
}

**Comment by jimharris** [comment]
http://10.102.17.206/private_build/autotest-per-patch_47796.html

**Comment by jessehui** [comment]
Reproduce on an Optane P4800X, can't reproduce on P4510 with OPAL enabled. I will see if I can fix or if it is a firmware related error. Thanks for reporting.

**Comment by jimharris** [comment]
I saw this reply from @jessehui over e-mail, but for some reason it didn't persist on GitHub.

"Unbind from UIO, and then run nvme reset can fix in my environment. This is due to trying too many times for auth session with wrong password. I am not quite sure why this can be triggered."

**Comment by jimharris** [comment]
@jessehui - can you provide guidance on next steps?  If we see more of these failures we will likely need to disable this test.

**Comment by jessehui** [comment]
For locked out during authenticate session, nvme reset can help. But for admin session for example take ownership or revert operations, this doesn't seem to help. Based on Opal spec, a power cycle should fix this failure, however, I can't get rid of this failure by doing a power cycle for Optane P4800X. Opal autotest is disabled until we know how to fix this. Thank you.

**Comment by jessehui** [comment]
However, I still don't understand why it get "Authority Locked Out" in our test environment. Based on my test, it will only throw this error message after 6 times wrong input. I think we can loop in @karlatec and see how we can avoid this error.

**Comment by jessehui** [comment]
OK. For an initialized device, if we try init it again and again for several times, it can still get locked out. Or for an non-initialized device, if we do revert again and again for several times, it can also get locked out.
Since we have revert process in autotest.sh. I guess this is called too many times. This is a behaviour defined by firmware.

**Comment by jessehui** [comment]
This patch should fix. https://review.gerrithub.io/c/spdk/spdk/+/472530

**Comment by tomzawadzki** [comment]
Bug scrub: @karlatec Tested the patch, but it didn't seem to solve the issue. @karlatec Can you please update here (and linked patch) with details?

**Comment by jimharris** [comment]
Removing "Intermittent Failure" label from this patch for now, since Opal tests have been removed from the test pool.  It also seems this issue can be easily reproduced outside of the test pool.

**Comment by karlatec** [comment]
So I manually tested this patch yesterday and funny stuff was happening. It's not "AUTHORITY LOCKED OUT" error anymore, but still errors. Could be related.

Here are the steps which I did. OS is F29 5.1.11-200.fc29.x86_64.
Used commit:
```
[sys_sgci@localhost spdk]$ git log --oneline -5
813363891 (HEAD) Opal: Add a state machine
a4925ba74 nvme: take the lock when disconnecting qpairs.
4121477d9 lib/vmd: make sure pcie_cap is not NULL before dereferencing it
efbcd259a (tag: v19.10-rc1) lib/nvme: nvme character device tests
eafc447ec changelog: add reset handling APIs
```
Too bad it wasn't rebased.

Steps:
1. Compile SPDK with ./configure --enable-debug

2. Run app/spdk_tgt/spdk_tgt and attach NVMe
```
[sys_sgci@localhost spdk]$ Starting SPDK v19.10-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid123790 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 639:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 0

[sys_sgci@localhost spdk]$ sudo scripts/rpc.py bdev_nvme_attach_controller -b nvme0 -t pcie -a 0000:83:00.0
EAL:   using IOMMU type 1 (Type 1)
nvme0n1
```

3. Init OPAL on NVMe bdev, looks OK
```
[sys_sgci@localhost spdk]$ sudo scripts/rpc.py bdev_nvme_opal_init -b nvme0 -p test
```

4. Create OPAL bdev; there are errors, but RPC returns bdev name as if it was successful.
```
[sys_sgci@localhost spdk]$ sudo scripts/rpc.py bdev_opal_create -b nvme0 -n 1 -i 1 -s 0 -l 1024 -p test
nvme_qpair.c: 138:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:191 nsid:1 lba:0 len:64
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: ACCESS DENIED (02/86) sqid:1 cid:191 cdw0:0 sqhd:0001 p:1 m:0 dnr:1
vbdev_gpt.c: 439:spdk_gpt_bdev_complete: *ERROR*: Gpt: bdev=nvme0n1r1 io error status=0
nvme0n1r1
```

5. Delete OPAL bdev
```
[sys_sgci@localhost spdk]$ sudo scripts/rpc.py bdev_opal_delete -b nvme0n1r1 -p test
[sys_sgci@localhost spdk]$ echo $?
0
```

6. Revert OPAL bdev
```
[sys_sgci@localhost spdk]$ sudo scripts/rpc.py bdev_nvme_opal_revert -b nvme0 -p test
[sys_sgci@localhost spdk]$ echo $?
0
```

7. Initialize OPAL bdev again
```
[sys_sgci@localhost spdk]$ sudo scripts/rpc.py bdev_nvme_opal_init -b nvme0 -p test
nvme_opal.c:1822:spdk_opal_cmd_take_ownership: *ERROR*: Device Busy
vbdev_opal_rpc.c:  87:spdk_rpc_bdev_nvme_opal_init: *ERROR*: Take ownership failure: -16
request:
{
  "method": "bdev_nvme_opal_init",
  "req_id": 1,
  "nvme_ctrlr_name": "nvme0",
  "password": "test"
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "SP Busy, try again later"
}
```

8. Try to revert it
```
[sys_sgci@localhost spdk]$ sudo scripts/rpc.py bdev_nvme_opal_revert -b nvme0 -p test
nvme_opal.c:2170:spdk_opal_cmd_revert_tper_async: *ERROR*: Device Busy
vbdev_opal.c: 609:spdk_vbdev_opal_revert_tper: *ERROR*: nvme0 revert tper failure: -16
vbdev_opal_rpc.c: 181:spdk_rpc_bdev_nvme_opal_revert: *ERROR*: Revert TPer failure: -16
request:
{
  "method": "bdev_nvme_opal_revert",
  "req_id": 1,
  "nvme_ctrlr_name": "nvme0",
  "password": "test"
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "Internal error"
}
```

9. Try Init again
```
[sys_sgci@localhost spdk]$ sudo scripts/rpc.py bdev_nvme_opal_init -b nvme0 -p test
nvme_opal.c: 429:opal_response_parse: *ERROR*: Bad header length. cp: 0, pkt: 0, subpkt: 0
nvme_opal.c: 638:opal_parse_and_check_status: *ERROR*: Couldn't parse response.
nvme_opal.c:1836:spdk_opal_cmd_take_ownership: *ERROR*: start admin SP session error -22: UNKNOWN ERROR
nvme_opal.c: 429:opal_response_parse: *ERROR*: Bad header length. cp: 0, pkt: 0, subpkt: 0
nvme_opal.c: 638:opal_parse_and_check_status: *ERROR*: Couldn't parse response.
vbdev_opal_rpc.c:  87:spdk_rpc_bdev_nvme_opal_init: *ERROR*: Take ownership failure: -22
request:
{
  "method": "bdev_nvme_opal_init",
  "req_id": 1,
  "nvme_ctrlr_name": "nvme0",
  "password": "test"
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "Internal error"
}
```

10. Kill SPDK & Try again.
At this point after sending SIGTERM (Ctrl-C) to SPDK, it stuck. I had to kill it with SIGKILL eventually after waiting a couple of minutes.

11. Start SPDK & attach NVMe bdev
```
[sys_sgci@localhost spdk]$ sudo app/spdk_tgt/spdk_tgt &
[1] 123888
[sys_sgci@localhost spdk]$ Starting SPDK v19.10-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid123889
 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 639:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 0

[sys_sgci@localhost spdk]$ sudo scripts/rpc.py bdev_nvme_attach_controller -b nvme0 -t pcie -a 0000:
83:00.0
EAL:   using IOMMU type 1 (Type 1)
packet_write_wait: Connection to 10.102.17.92 port 22: Broken pipe
```
**At this point SPDK hanged after sending bdev_nvme_attach_controller via rpc.py. It stuck for about 1-2 minutes and then the platform got rebooted** (I had KVM open in other window so I was looking at the console screen).

I tried to look up the reason of fail in /var/log/messages and via journalctl --boot=-1, but there was nothing logged. Last lines from these logs match the last OPAL error messages from SPDK and there's nothing more after that:
```
Nov 06 10:40:50 localhost.localdomain spdk[123790]: nvme_opal.c: 429:opal_response_parse: *ERROR*: Bad header length. cp: 0, pkt: 0, subpkt: 0
Nov 06 10:40:50 localhost.localdomain spdk[123790]: nvme_opal.c: 638:opal_parse_and_check_status: *ERROR*: Couldn't parse response.
Nov 06 10:40:50 localhost.localdomain spdk[123790]: nvme_opal.c:1836:spdk_opal_cmd_take_ownership: *ERROR*: start admin SP session error -22: UNKNOWN ERROR
Nov 06 10:40:50 localhost.localdomain spdk[123790]: nvme_opal.c: 429:opal_response_parse: *ERROR*: Bad header length. cp: 0, pkt: 0, subpkt: 0
Nov 06 10:40:50 localhost.localdomain spdk[123790]: nvme_opal.c: 638:opal_parse_and_check_status: *ERROR*: Couldn't parse response.
Nov 06 10:40:50 localhost.localdomain spdk[123790]: vbdev_opal_rpc.c:  87:spdk_rpc_bdev_nvme_opal_init: *ERROR*: Take ownership failure: -22
Nov 06 10:40:50 localhost.localdomain sudo[123836]: pam_unix(sudo:session): session closed for user root
Nov 06 10:40:50 localhost.localdomain audit[123836]: USER_END pid=123836 uid=0 auid=1000 ses=3 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix ac>
Nov 06 10:40:50 localhost.localdomain audit[123836]: CRED_DISP pid=123836 uid=0 auid=1000 ses=3 msg='op=PAM:setcred grantors=pam_env,pam_fprintd acct="root" exe="/usr/bin/sudo" hostname=? addr=? term>
Nov 06 10:42:33 localhost.localdomain audit[123849]: CRYPTO_KEY_USER pid=123849 uid=0 auid=4294967295 ses=4294967295 msg='op=destroy kind=server fp=SHA256:17:7d:c2:8c:f5:30:10:47:db:6b:98:3f:d9:0d:e0>
Nov 06 10:42:33 localhost.localdomain audit[123849]: CRYPTO_KEY_USER pid=123849 uid=0 auid=4294967295 ses=4294967295 msg='op=destroy kind=server fp=SHA256:f8:30:e7:ae:63:10:cf:6c:41:92:4f:64:3c:a9:e2>
```

**Also, after rebooting the OS does not detect the NVMe drive:**
```
[sys_sgci@localhost spdk]$
[sys_sgci@localhost spdk]$ sudo nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------



[sys_sgci@localhost spdk]$ sudo scripts/setup.sh status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB        0 /      0
node1   1048576kB        0 /      0
node1      2048kB        0 /      0

NVMe devices
BDF             Vendor  Device  NUMA    Driver          Device name

I/OAT DMA
BDF             Vendor  Device  NUMA    Driver
0000:00:04.0    8086    0e20    0       ioatdma
0000:80:04.0    8086    0e20    1       ioatdma
0000:00:04.1    8086    0e21    0       ioatdma
0000:80:04.1    8086    0e21    1       ioatdma
0000:00:04.2    8086    0e22    0       ioatdma
0000:80:04.2    8086    0e22    1       ioatdma
0000:00:04.3    8086    0e23    0       ioatdma
0000:80:04.3    8086    0e23    1       ioatdma
0000:00:04.4    8086    0e24    0       ioatdma
0000:80:04.4    8086    0e24    1       ioatdma
0000:00:04.5    8086    0e25    0       ioatdma
0000:80:04.5    8086    0e25    1       ioatdma
0000:00:04.6    8086    0e26    0       ioatdma
0000:80:04.6    8086    0e26    1       ioatdma
0000:00:04.7    8086    0e27    0       ioatdma
0000:80:04.7    8086    0e27    1       ioatdma

virtio
BDF             Vendor  Device  NUMA    Driver          Device name
VMD
BDF             Numa Node       Driver Name

[sys_sgci@localhost spdk]$ dmesg | grep -i nvme
[sys_sgci@localhost spdk]$ echo $?
1

```

**Comment by jessehui** [comment]
Hi Karol, it is a patch series. Sorry to mention, please use the top commit and test again. For example, at this moment, it is `https://review.gerrithub.io/c/spdk/spdk/+/473383/1` .Thank you.

**Comment by jessehui** [comment]
This also may not happen if you could just wait until the revert process is done.  

As we are using Optane P4800X as the Opal test drive which is using old version hardware and firmware and make it very slow to revert. If you force killing the process, opal command only succeed sending nvme security send and not nvme security receive which will cause admin command sequence error next time when another NVMe admin command is issued. Thus that's the reason I put comments in nvme_manage revert option saying that `Please don't ternminate this excecution. Otherwise undefined error may occur`.

**Comment by karlatec** [comment]
> hus that's the reason I put comments in nvme_manage revert option saying that Please don't ternminate this excecution. Otherwise undefined error may occur.

Does it show up when executing RPC commands? I am searching through the bash log as I still have the output in my session window and I don't see any message like that.
Also - revert rpc was really quick. If it's a long process, shouldn't we block & wait for the revert to complete and then finish the rpc response?

**Comment by jessehui** [comment]
However, using that single commit can still fix this in my environment. Please use the latest commit and rebase.

After you send an Opal revert command, if you continue sending init/revert command, on target side, you will always get:
```shell
nvme_opal.c:1822:spdk_opal_cmd_take_ownership: *ERROR*: Device Busy
vbdev_opal_rpc.c:  87:spdk_rpc_bdev_nvme_opal_init: *ERROR*: Take ownership failure: -16
nvme_opal.c:2170:spdk_opal_cmd_revert_tper_async: *ERROR*: Device Busy
vbdev_opal.c: 609:spdk_vbdev_opal_revert_tper: *ERROR*: nvme0 revert tper failure: -16
vbdev_opal_rpc.c: 181:spdk_rpc_bdev_nvme_opal_revert: *ERROR*: Revert TPer failure: -16
nvme_opal.c:1822:spdk_opal_cmd_take_ownership: *ERROR*: Device Busy
vbdev_opal_rpc.c:  87:spdk_rpc_bdev_nvme_opal_init: *ERROR*: Take ownership failure: -16
```

And on client side:
```shell
ᐅ ./scripts/rpc.py bdev_nvme_opal_init -b nvme0 -p test
request:
{
  "method": "bdev_nvme_opal_init",
  "req_id": 1,
  "nvme_ctrlr_name": "nvme0",
  "password": "test"
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "SP Busy, try again later"
}
```
```shell
ᐅ ./scripts/rpc.py bdev_nvme_opal_revert -b nvme0 -p test
request:
{
  "method": "bdev_nvme_opal_revert",
  "req_id": 1,
  "nvme_ctrlr_name": "nvme0",
  "password": "test"
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "Internal error"
}
```
It will always be like this until the revert is done.
I believe the weird or funny stuff you mention is due to you kill the process before revert is done.

**Comment by jessehui** [comment]
> > hus that's the reason I put comments in nvme_manage revert option saying that Please don't ternminate this excecution. Otherwise undefined error may occur.
> 
> Does it show up when executing RPC commands? I am searching through the bash log as I still have the output in my session window and I don't see any message like that.
> Also - revert rpc was really quick. If it's a long process, shouldn't we block & wait for the revert to complete and then finish the rpc response?

It is not shown because I want to make it work even if you kill the process before the revert is done. And that's the reason I ask you to use the patch series not just this single commit. Please take a look on https://review.gerrithub.io/c/spdk/spdk/+/472591/5. Thank you.

We don't block and wait because the revert process can be very long and the rpc can get timeout. That's the reason we make it async and return quickly. You can keep doing other IOs after sending revert command, it will only loop and wait for complete when destruct the NVMe bdev beneath it.

**Comment by karlatec** [comment]
So if that's by design then the problem is in documentation. From what I see nvme_manage.c is the only place that mentions not to interrupt the revert process, and I don't see anything in documentation (or in rpc.py help) with a warning that revert takes place in the  background and can take a long time. So from the user perspective - I am totally unaware of that.

Next thing is the unexpected reboot - unfortunately there are no logs available and I've been able to reproduce that on second server.
And one final thing is the NVMe being unavailable after reboot. With the help of one of the team we've been able to see that the NVMe's on both servers hit the assert condition *ASSERT_FFFF021C which they described as "firmware accessed a memory region it was not supposed to access". 

@jimharris can you take a look here?

**Comment by karlatec** [comment]
If the idea is not to interrupt the process while the revert is in progress then it doesn't really fit to our CI flow. We kill the processes and exit on first encountered error, and reboot almost immediately. I am afraid that this would have the same results on the disks as my manual steps.
**This is rather serious as local nsg folks are unable to bring back affected nvmes back to life.**

**Comment by jimharris** [comment]
The opal bdev definitely needs to be more robust before we can re-enable these CI tests.  CI will sometimes kill tests while they are running - that cannot render an SSD unusable.

@jessehui - please run tests on your local system similar to what @karlatec described above.  If there are specific P4800X FW revisions needed, let's make sure we also have those in the test pool.

**Comment by jessehui** [comment]
Are you using a VM? I can't reproduce under a physical server.

**Comment by karlatec** [comment]
> Are you using a VM? I can't reproduce under a physical server.
Physical system.

> The error response you get seems that you didn't get the patch build.
100% sure I built it after I did git fetch.

**Comment by jessehui** [comment]
I think it might be related with IOMMU. I don't think I have that enabled. But it seems you do. I will take a try.

**Comment by karlatec** [comment]
Yup, it is enabled

```
[sys_sgci@localhost spdk]$ cat /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="resume=UUID=249288a5-d0ad-4062-8c6a-b4edd5a2d9d2 rhgb quiet iommu=pt intel_iommu=on"
GRUB_DISABLE_RECOVERY="true"
[sys_sgci@localhost spdk]$ lsmod | grep vfio
vfio_pci               61440  0
vfio_virqfd            16384  1 vfio_pci
vfio_iommu_type1       32768  0
vfio                   36864  2 vfio_iommu_type1,vfio_pci
irqbypass              16384  2 vfio_pci,kvm

```

**Comment by jessehui** [comment]
After IOMMU and VFIO enabled, I still can't reproduce this error. I think what you receive at `step 9` is pretty wierd. If you take a look at the code, before revert is done, the state is always busy. And thus it should return exactly the same error as `step 7`. 
And even if you kill the target before revert is done, you should receive COMMAND SEQUENCE ERROR which is shown in my previous post. 
Opal command is only send via NVMe admin command security send/receive which are defined by NVMe SPEC and should never touch firmware.

**Comment by jimharris** [comment]
[Bug scrub] Marking as medium bug - Changpeng is looking at this further.

**Comment by optimistyzy** [comment]
@changpe1 I know  that you take over this work. Is this issue solved?

**Comment by changpe1** [comment]
> @changpe1 I know that you take over this work. Is this issue solved?

It should be some firmware issue that the revert will take too much time on P4800x, https://review.spdk.io/gerrit/c/spdk/spdk/+/2816 will enable OPAL on P4510 drives, we can add more supported drives after verification.

**Comment by changpe1** [comment]
Mark this issue as third party issue.  Optane SSD uses bit based medium, so when formatting a namespace or doing security revert operation, the drive will take much longer time that NAND based SSDs, our test case will be aborted after 15m, the drive may still in the revert status.

For now we enabled the OPAL tests with P4510 drives, so closing this issue for now.
