### ISSUE TITLE
SPDK can't set the NVMe SSD behind VMD which are connected by pcie ssd switch

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#1055]
## Expected Behavior
all nvme ssd should be recognized by spdk_lspci tool.
## Current Behavior
one nvme ssd which is connected by pcie ssd switch can't be recognized by spdk_lspci tool.
## Steps to Reproduce
1. use pcie ssd switch to connect nvme ssd with the U.2 port;
2. setup VMD in the BIOS for all PCI;
3. get the 201d devices:
```
17:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)
5d:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)
85:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)
ae:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)
d7:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)

```
4. get the current nvme devices config:
```
10001:02:00.0 Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)
10003:08:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500
10004:02:00.0 Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)

```
5. Run following command to setup pcie devices
PCI_WHITELIST="0000:17:05.5 0000:5d:05.5 0000:85:05.5 0000:ae:05.5 0000:d7:05.5" ./scripts/setup.sh
6. run spdk_lspci tool:
```
[]# ./app/spdk_lspci/spdk_lspci
Starting SPDK v20.01-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: spdk_lspci --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid4915 ]
EAL: No available hugepages reported in hugepages-1048576kB

List of available PCI devices:
5d0505:03:00.0 (8086 953) (NVMe disk behind VMD)
d70505:03:00.0 (8086 953) (NVMe disk behind VMD)
0000:17:05.5 (8086 201d) (VMD)
0000:5d:05.5 (8086 201d) (VMD)
0000:85:05.5 (8086 201d) (VMD)
0000:ae:05.5 (8086 201d) (VMD)
0000:d7:05.5 (8086 201d) (VMD)

```

**Comment by jimharris** [comment]
Hi Liang,

Could you figure out which one of the three SSDs is not appearing?  I think there's a way to check the Linux lspci output to see which VMD endpoint each VMD PCI domain is associated with.

I see that 10003:08:00.0 is different SSD type than the other two - I'm wondering if that is the SSD that's not appearing.

I'm assigning to @ksztyber who may be able to provide additional debug steps.

Thanks,

-Jim

**Comment by liang2yan** [comment]
Hi Jim,

Yes, the SSD "10003:08:00.0" disappeared. and after running spdk_lspci tool, I run "lspci|grep -i vola" command. this command don't have output, all three nvme ssd disappeared.

**Comment by ksztyber** [comment]
Hi @liang2yan,
the fact the all of the SSDs disappear from `lspci` is expected, as you're unbinding kernel's PCIe driver from the VMD devices when calling `scripts/setup.sh`. Of course once this is done, they all should appear in the output of `spdk_lspci`.

Are all of the drives behind the switch or just the one that disappears?

Could you post the output from `examples/vmd/lsvmd/lsvmd -d`?

**Comment by liang2yan** [comment]
@ksztyber , please see attached file. 
[vmd1055.log](https://github.com/spdk/spdk/files/3856952/vmd1055.log)

**Comment by ksztyber** [comment]
It looks like the device behind the switch cannot be assigned base addresses (vmd_assign_base_addrs fails). I've posted a patch adding a few more debug logs, that should help in pinpointing the exact issue: https://review.gerrithub.io/c/spdk/spdk/+/474997
@liang2yan, could you apply this patch and rerun `lsvmd -d`?

**Comment by liang2yan** [comment]
@ksztyber , please see the attached file. it is the log with your patch.
[newvmd1055.log](https://github.com/spdk/spdk/files/3861534/newvmd1055.log)

**Comment by liang2yan** [comment]
@ksztyber , any update? Some users are trying vmd module. They may met same issues. so we need to fix this issue soon.

**Comment by ksztyber** [comment]
I'm working on setting up a similar configuration, so that I could reproduce it.
In the meantime, could you check if the first call to `lsvmd` shows the SSD behind the VMD? I suspect that the issue might be related to the way the VMD code uses config bars to save the base/limit registers and use them during subsequent enumerations. There are two ways of resetting those values: rebooting the machine or calling `scripts/setup.sh reset`. Could you try the following two scenarios:
1. `scripts/setup.sh reset`
2. `scripts/setup.sh`
3. `examples/vmd/lsvmd/lsvmd -d`
and
1. reboot the server
2. `scripts/setup.sh`
3. `examples/vmd/lsvmd/lsvmd -d`
Please save the logs and upload them here. It'd also be helpful if you did using the patch I've posted previously.

**Comment by liang2yan** [comment]
@ksztyber , please check the log.
[vmd1121.log](https://github.com/spdk/spdk/files/3872605/vmd1121.log)

I followed your steps except i rebooted the machines before the first step 2. So I don't need to run the first step 1.

**Comment by ksztyber** [comment]
@liang2yan, could you test the following patch: https://review.gerrithub.io/c/spdk/spdk/+/475716

**Comment by liang2yan** [comment]
@ksztyber , I have tried your patch. the lsvmd command only can show the NVMe SSD connected by pcie ssd switch after the second running. It means that the following scenario:
1. run "examples/vmd/lsvmd/lsvmd -d" command, the output will not show the NVMe SSD connected by pcie ssd switch;
2.run "examples/vmd/lsvmd/lsvmd -d" command again, the output will  show the NVMe SSD connected by pcie ssd switch.
Please see the attach file for the detailed log:
[vmd1126.log](https://github.com/spdk/spdk/files/3890031/vmd1126.log)

**Comment by ksztyber** [comment]
@liang2yan, could you test this patch: https://review.gerrithub.io/c/spdk/spdk/+/475832

The logs show that you have some kind of network device (8086:1593, which google tells me is an Intel's e810  NIC), that tries map more memory than was available for that VMD adapter, which resulted in depleting that adapter's memory region. The patch should fix that, so that the region is only padded once we know it's possible to map the device.

However, I don't think it makes sense to this kind of device behind the VMD. I suggest checking your VMD configuration and making sure only NVMe devices are selected to be behind the VMD.

**Comment by liang2yan** [comment]
@ksztyber , just tried your patches. the lsvmd tool can show the NVMe SSD connected by pcie switch now. I have set all three nvme sdd to be connected by pcie switch. the lsvmd tool can still show them.
please check the log below:
[1127vmd.log](https://github.com/spdk/spdk/files/3895264/1127vmd.log)

**Comment by ksztyber** [comment]
That's great. Could you also run `test/vmd/vmd.sh` a couple of times to make sure everything is working correctly?

**Comment by liang2yan** [comment]
I have run test/vmd/vmd.sh 100 times. No errors found.

**Comment by ksztyber** [comment]
Great news! Could you test it one more time using the following version: https://review.gerrithub.io/c/spdk/spdk/+/476163
It's a cleaned up version that should be more robust and generic, but I'd like to confirm it does work on your config too.

**Comment by liang2yan** [comment]
@ksztyber , I used your patch series.  the vmd.sh script can be executed 100 times without error.

**Comment by ksztyber** [comment]
@liang2yan Could you verify that the code merged to master (ef8966f) works and close this issue?
Thanks.

**Comment by liang2yan** [comment]
I run test/vmd/vmd.sh 100 time with latest codes, no error found. so close this issue.
