### ISSUE TITLE
[clang-vg-auotest] dpdk submodule fails to build with clang version 13.0.0 on Fedora35

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2274]
# Bug report

As in title. DPDK submodule in SPDK fails to build under Fedora 35 OS.

## Current Behavior

```
00:12:16.224  [57/356] Compiling C object lib/librte_eal.a.p/eal_unix_rte_thread.c.o
00:12:16.224  [58/356] Compiling C object lib/librte_eal.a.p/eal_linux_eal_cpuflags.c.o
00:12:16.224  [59/356] Compiling C object lib/librte_eal.a.p/eal_common_eal_common_options.c.o
00:12:16.224  [60/356] Compiling C object lib/librte_eal.a.p/eal_linux_eal_debug.c.o
00:12:16.481  [61/356] Compiling C object lib/librte_eal.a.p/eal_linux_eal.c.o
00:12:16.481  FAILED: lib/librte_eal.a.p/eal_linux_eal.c.o 
00:12:16.481  /usr/bin/clang -Ilib/librte_eal.a.p -Ilib -I../lib -I. -I.. -Iconfig -I../config -Ilib/eal/include -I../lib/eal/include -Ilib/eal/linux/include -I../lib/eal/linux/include -Ilib/eal/x86/include -I../lib/eal/x86/include -Ilib/eal/common -I../lib/eal/common -Ilib/eal -I../lib/eal -Ilib/kvargs -I../lib/kvargs -Ilib/metrics -I../lib/metrics -Ilib/telemetry -I../lib/telemetry -I/home/vagrant/spdk_repo/spdk/intel-ipsec-mb/lib -I/home/vagrant/spdk_repo/spdk/isa-l -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -include rte_config.h -Wextra -Wcast-qual -Wdeprecated -Wformat -Wformat-nonliteral -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-address-of-packed-member -Wno-missing-field-initializers -D_GNU_SOURCE -fPIC -Werror -fPIC -march=native -DALLOW_EXPERIMENTAL_API -DALLOW_INTERNAL_API '-DABI_VERSION="21.3"' -DRTE_LIBEAL_USE_GETENTROPY -DRTE_LOG_DEFAULT_LOGTYPE=lib.eal -MD -MQ lib/librte_eal.a.p/eal_linux_eal.c.o -MF lib/librte_eal.a.p/eal_linux_eal.c.o.d -o lib/librte_eal.a.p/eal_linux_eal.c.o -c ../lib/eal/linux/eal.c
00:12:16.481  ../lib/eal/linux/eal.c:565:11: error: variable 'total_mem' set but not used [-Werror,-Wunused-but-set-variable]
00:12:16.481          uint64_t total_mem = 0;
00:12:16.481                   ^
00:12:16.481  1 error generated.
00:12:16.481  [62/356] Compiling C object lib/librte_eal.a.p/eal_linux_eal_alarm.c.o
00:12:16.481  [63/356] Compiling C object lib/librte_eal.a.p/eal_linux_eal_dev.c.o
00:12:16.481  [64/356] Compiling C object lib/librte_eal.a.p/eal_linux_eal_log.c.o
00:12:16.481  [65/356] Compiling C object lib/librte_eal.a.p/eal_linux_eal_lcore.c.o
00:12:16.481  [66/356] Compiling C object lib/librte_eal.a.p/eal_linux_eal_hugepage_info.c.o
```

## Possible Solution

Either disable fail on warning, update submodule or report to DPDK for fix.

## Steps to Reproduce

1. Build SPDK on recent Fedora 35 release using clang.
My build was with: 
```
./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --with-nvme-cuse --with-pmdk --with-reduce --with-rbd --with-crypto --with-ocf --enable-ubsan --enable-asan --enable-coverage --with-fuse --with-raid5 --with-uring
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK 91b8cd37915ccca471ec3c23b73a5e5b72911616
OS: Fedora 35 Linux fedora35-cloud-211209686 5.15.6-200.fc35.x86_64 #1 SMP Wed Dec 1 13:41:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
clang version 13.0.0 (Fedora 13.0.0-3.fc35)

**Comment by jimharris** [comment]
I've already fixed this in upstream DPDK:  https://github.com/DPDK/dpdk/commit/628bac7df18904c7083c8ad04669c69688f352de

So I think what we need here is back porting this into our DPDK fork until we move our submodule to include this fix.

**Comment by karlatec** [comment]
Thanks for a quick reply Jim!
Cherry picked the fix into our spdk/dpdk 21.08 branch: https://review.spdk.io/gerrit/c/spdk/dpdk/+/10613

**Comment by jimharris** [comment]
Here are some other patches I pushed for clang-13.  I'm guessing you'll run into these next.  :)


https://github.com/DPDK/dpdk/commit/1345c5baae35d16b20126704c8636c476c4f32eb
https://github.com/DPDK/dpdk/commit/0353121c33846c40ff2e2282448f324c93d3ce9d
https://github.com/DPDK/dpdk/commit/d4fb4eb08725a3e667042c1f5cd3ed72b94505a7

**Comment by karlatec** [comment]
Prophet :) Yes, one of these. I'm guessing the rest will come in handy when updating our submodule to DPDK 21.11.

For now, this series seems to be enough to fix spdk/dpdk 21.08:
https://review.spdk.io/gerrit/c/spdk/dpdk/+/10624/1

I still see some warnings from ipsec submodule, but that's a different story:
```
09:24:18  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:18  sse/zuc_sse_top.c:1059:26: warning: variable 'L' set but not used [-Wunused-but-set-variable]
09:24:18                  uint32_t L = ((N + 31) / ZUC_WORD_BITS) -
09:24:18                           ^
09:24:18  no-aesni/zuc_sse_no_aesni_top.c:950:26: warning: variable 'L' set but not used [-Wunused-but-set-variable]
09:24:18                  uint32_t L = ((N + 31) / ZUC_WORD_BITS) -
09:24:18                           ^
09:24:18  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:18  1 warning generated.
09:24:18  1 warning generated.
09:24:18  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:18  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:18  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:18  avx/zuc_avx_top.c:912:26: warning: variable 'L' set but not used [-Wunused-but-set-variable]
09:24:18                  uint32_t L = ((N + 31) / ZUC_WORD_BITS) -
09:24:18                           ^
09:24:18  avx512/zuc_avx512_top.c:559:18: warning: variable 'L' set but not used [-Wunused-but-set-variable]
09:24:18          uint32_t L = (N + 31) / ZUC_WORD_BITS;
09:24:18                   ^
09:24:18  avx512/zuc_avx512_top.c:655:26: warning: variable 'L' set but not used [-Wunused-but-set-variable]
09:24:18                  uint32_t L = ((N + 31) / ZUC_WORD_BITS) -
09:24:18                           ^
09:24:18  avx2/zuc_avx2_top.c:888:26: warning: variable 'L' set but not used [-Wunused-but-set-variable]
09:24:18                  uint32_t L = ((N + 31) / ZUC_WORD_BITS) -
09:24:18                           ^
09:24:19  1 warning generated.
09:24:19  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:19  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:19  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:19  2 warnings generated.
09:24:19  1 warning generated.
09:24:19  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:19  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:19  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:20  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:20  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
09:24:20  clang-13: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
```

**Comment by tomzawadzki** [comment]
[Bug scrub] Submodule update to include clang fixes is now merged. Issue can be closed.
