### ISSUE TITLE
In the rdma environment, vhost has high latency in processing large size IO

### ISSUE THREAD

**Issue by xupeng-mingtu** [spdk/spdk#3705]
# Sighting report

In the rdma environment, vhost has high latency in processing large size IO

## Expected Behavior

low latency

## Current Behavior

vhost has high latency in processing large size IO

## Possible Solution

not sure

## Steps to Reproduce

1. build a VM, start fio with large size IO(eg. 512k) and 32 QD

## Context (Environment including OS version, SPDK version, etc.)

SPDK v24.01
RDMA NIC: Mellanox Technologies MT2894 Family [ConnectX-6 Lx]

**Comment by xupeng-mingtu** [comment]
@AlekseyMarchuk Do you have any suggestions on this issue?

**Comment by AlekseyMarchuk** [comment]
Hi @xupeng-mingtu, there were several improvements (and bug fixes for those improvements) after v24.01 for this issue. Can you update your SPDK version to v25.05? Or at least update code in rdma.c

**Comment by xupeng-mingtu** [comment]
> improvements

OK, I will try the v25.05. Could you give some key words for those improvements?

**Comment by xupeng-mingtu** [comment]
> Hi [@xupeng-mingtu](https://github.com/xupeng-mingtu), there were several improvements (and bug fixes for those improvements) after v24.01 for this issue. Can you update your SPDK version to v25.05? Or at least update code in rdma.c

@AlekseyMarchuk OK, I will try the v25.05. Could you give some key words for those improvements?

**Comment by AlekseyMarchuk** [comment]
In RDMA_REQ_TX_PENDING_H2C state we are limited by max outstanding RDMA_READ's supported by HW, for Mellanox cards that is 16. If I remember correctly, before improvements we tried to submit all necessary RDMA_READ's, if allowed qdepth was smaller then we did nothing. With the improvement we utilised all available RDMA_READ slots by splitting required number of operations into several parts, as result IO request spends less time in the RDMA_REQ_TX_PENDING_H2C state. Please note that there were some side effects/bugs that were fixed later

**Comment by xupeng-mingtu** [comment]
@AlekseyMarchuk Hi, I have updated the nvmf-tgt to v25.05.x, but the issue still exists. Is the throughput of a single RDMA qpair limiting the IO processing capability?

**Comment by tomzawadzki** [comment]
[Bug scrub] @AlekseyMarchuk Is there any other information that would be helpful with addressing the issue here ?

**Comment by AlekseyMarchuk** [comment]
rdma qpair supports a limited number of outstanding RDMA_READ operations, in NVIDIA cards that is 16 requests per qpair. We need to wait for outstanding RDMA_READs to complete before posting a new portion. With big and fragmented Write IOs that can lead to increased latency. @xupeng-mingtu were you able to reproduce big IO latency in simpler environment, without vhost?

**Comment by xupeng-mingtu** [comment]
> rdma qpair supports a limited number of outstanding RDMA_READ operations, in NVIDIA cards that is 16 requests per qpair. We need to wait for outstanding RDMA_READs to complete before posting a new portion. With big and fragmented Write IOs that can lead to increased latency. [@xupeng-mingtu](https://github.com/xupeng-mingtu) were you able to reproduce big IO latency in simpler environment, without vhost?

@AlekseyMarchuk I haven't done this kind of test before. Do you mean testing without a vhost or without RDMA?

If the performance degradation is indeed due to the read concurrency limit of the RDMA card, I'd like to know if this performance is as expected under this load? I didn't find any scenarios involving large-size I/O and high throughput in the SPDK test reports.

**Comment by AlekseyMarchuk** [comment]
@xupeng-mingtu can you try your test without vhost?
SPDK performance reports use 128K IO size, but I'd say that the IO size here is not as important as its fragmentation. As I wrote above, Nvidia NICs support up to 16 RDMA_READ operations per qp, all other RDMA_READ are queued, that adds network round trip latency to the request. In the worst case RDMA target may submit RDMA_READs in 2 batches.
