### ISSUE TITLE
bdev_nvme: failed assert in bdev_nvme_clear_io_path_caches/spdk_for_each_channel

### ISSUE THREAD

**Issue by plestk** [spdk/spdk#3736]
I got a failed assert while running v24.01:

```
Stack trace of thread 9439:
#0  0x00007f176844e52f raise (libc.so.6)
#1  0x00007f1768421e65 abort (libc.so.6)
#2  0x00007f1768421d39 __assert_fail_base.cold.0 (libc.so.6)
#3  0x00007f1768446e86 __assert_fail (libc.so.6)
#4  0x0000000000aeec4e spdk_for_each_channel (acs-tgt)
#5  0x0000000000426df4 bdev_nvme_clear_io_path_caches (acs-tgt)
#6  0x0000000000428ede bdev_nvme_poll_adminq (acs-tgt)
#7  0x0000000000adf7a5 thread_execute_timed_poller (acs-tgt)
```

with the following log message: `thread.c:26xx:spdk_for_each_channel: *ERROR*: could not find io_device 0x521005a60500`

I my understanding, this error happened because `bdev_nvme_poll_adminq`  was executed one last time after the `nvme_ctrlr` had unregistered as an IO device.

To avoid this error, I suggest to pause or remove the poller before calling `spdk_io_device_unregister` in `nvme_ctrlr_unregister`.

**Comment by jimharris** [comment]
Hi @plestk,

v24.01 is no longer supported. Can you reproduce on v25.01 or latest master?

Thanks,

Jim

**Comment by plestk** [comment]
Sadly I don't have time to reproduce on v25.01 or master. I'll go with the modification I suggested above. I posted this issue here, because I think it also affects later versions. Here are some more details: 

1. `nvme_ctrlr_unregister` is called with `adminq_timer_poller` active.
2. in `io_device_free` there is a `spdk_thread_send_msg` so `nvme_ctrlr_delete` is not called immediately. At this point `nvme_ctrlr` is not an IO device anymore.
3. `bdev_nvme_poll_adminq` is called because `adminq_timer_poller` is still active.
4. `bdev_nvme_clear_io_path_caches` is called and the assert fails because `nvme_ctrlr` is not an IO device anymore.

**Comment by shuhei-matsumoto** [comment]
@plestk Thank you for finding and analyzing this issue. I think you have a right fix. If possible, will you push your fix on the master to gerrit (https://spdk.io/development/) ?

**Comment by plestk** [comment]
https://review.spdk.io/c/spdk/spdk/+/26732

**Comment by plestk** [comment]
My understanding of the problem was wrong. The failed assert cannot be hit after the IO device has unregistered because of the check `nvme_ctrlr_is_available` in `bdev_nvme_clear_io_path_caches`.

The new hypothesis is the opposite. The assert failed because `bdev_nvme_poll_adminq` was called before the IO device had time to register. Further test/analysis is required to validate this new hypothesis though.

**Comment by jkalwas** [comment]
26732: bdev_nvme: pause the adminq poller before unregistering the ctrlr | https://review.spdk.io/c/spdk/spdk/+/26732

There is unresolved comment with solution proposed in patch linked, I'll try to look into this more.

**Comment by jkalwas** [comment]
Here is the patch proposal.

26926: bdev/nvme: register ctrlr early to avoid spdk_for_each_channel error | https://review.spdk.io/c/spdk/spdk/+/26926

While working on it, I found another race (addressed in the patch earlier in the series).

@plestk, by any chance, have you got a stable reproduction?
@shuhei-matsumoto, could you take a look?

**Comment by plestk** [comment]
@jkalwas I have a reproducer. I have inserted `system("sudo iptables -A INPUT -i <interface> -j DROP");` in `nvme_ctrlr_create` to fail the network at the right time (before `nvme_ctrlr_init_ana_log_page`). With ana reporting enabled on the target, the assert in spdk_for_each_channel fails.

**Comment by jkalwas** [comment]
Hi @plestk ,
I confirmed the fix with UT on top of it.
Could you also check if the fix works for you?

**Comment by plestk** [comment]
Unfortunately your patch does not fix my reproducer entirely. I still get a failed assert:
```
nvme_ctrlr_delete: Assertion `nvme_ctrlr->reset_detach_poller == NULL' failed
``` 
If I understand correctly there are two mechanisms: (1) a reconnect triggered from `bdev_nvme_reset_destroy_qpair_done` and (2) an unregister triggered from `nvme_ctrlr_init_ana_log_page_done`.

I don't see how to avoid the reconnect. Maybe `nvme_ctrlr_init_ana_log_page_done` should be more careful. This error path has probably never been tested.

Disclaimer: I am still running a custom branch based on 24.01

**Comment by jkalwas** [comment]
Actually, a completion error in `nvme_ctrlr_init_ana_log_page_done` shouldn’t be considered fatal. We’ve encountered similar cases during NVMe controller initialization - `lib/nvme` patches should be published soon.

Likely instead `nvme_ctrlr_unregister` and calling `populate_namespaces_cb` we should just proceed to `nvme_ctrlr_create_done` ...but other gotchas in `nvme_ctrlr_populate_namespaces` when reconnect is ongoing and with pending `nvme_async_probe_ctx` might pop up. @plestk could you give it a try as a short term fix?

I think we need the architectural solution, see the SPDK Slack thread
https://spdk-team.slack.com/archives/CRKHB75J8/p1760727149510239.
@shuhei-matsumoto your feedback is needed (I'm also not sure about background, feasibility or how much of work is that).

**Comment by shuhei-matsumoto** [comment]
@plestk Will you check my comment on https://review.spdk.io/c/spdk/spdk/+/26926 ? `bdev_nvme_delete_ctrlr()` should be able to handle correctly the race between nvme_ctrlr reconnect and nvme_ctrlr deletion. `nvme_ctrlr::resetting` and `nvme_ctrlr::destruct` are usable. @jkalwas, It may be good if we can move all ANA handling into lib/nvme, but I am not certain if it is really required and necessary.

**Comment by jkalwas** [comment]
I updated the patch to reflect @shuhei-matsumoto suggestion.

**Comment by plestk** [comment]
The latest version of the patch (Patchset 5) runs without error. It is good for me.
